import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    fontFamily: {
      sans: ["'Avenir'", "'Avenir Next'", "sans-serif"],
      mono: ["'Avenir'", "'Avenir Next'", "sans-serif"],
      serif: ["'Avenir'", "'Avenir Next'", "sans-serif"],
    },
    extend: {
      fontSize: {
        h1: ["56px", { lineHeight: "140%", fontWeight: "900" }],
        h2: ["48px", { lineHeight: "140%", fontWeight: "900" }],
        h3: ["34px", { lineHeight: "140%", fontWeight: "900" }],
        h4: ["24px", { lineHeight: "140%", fontWeight: "900" }],
        h5: ["20px", { lineHeight: "140%", fontWeight: "900" }],
        "large-heavy": ["18px", { lineHeight: "150%", fontWeight: "800" }],
        button: ["18px", { lineHeight: "150%", fontWeight: "800" }],
        "large-text": ["18px", { lineHeight: "150%", fontWeight: "500" }],
        "body-heavy": ["16px", { lineHeight: "150%", fontWeight: "800" }],
        body: ["16px", { lineHeight: "150%", fontWeight: "500" }],
        "small-heavy": ["14px", { lineHeight: "150%", fontWeight: "800" }],
        small: ["14px", { lineHeight: "150%", fontWeight: "500" }],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#38B1AF",
          foreground: "#FFFFFF",
          light: "#4CB9B7",
          50: "#F5FBFB",
          100: "#ECF8F7",
          200: "#D7EFEF",
          300: "#C4E8E7",
          400: "#AFE0DF",
          500: "#9CD8D7",
          600: "#88D0CF",
          700: "#74C9C7",
          800: "#60C1BF",
          900: "#4CB9B7",
          1000: "#38B1AF",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "#D71A1A",
          foreground: "#FFFFFF",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        coral: {
          DEFAULT: "#FF7C80",
          foreground: "#FFFFFF",
          50: "#FFF8F8",
          100: "#FFF2F3",
          200: "#FFE5E6",
          300: "#FFD8D9",
          400: "#FFCBCC",
          500: "#FFBEC0",
          600: "#FFB0B3",
          700: "#FFA4A7",
          800: "#FF9699",
          900: "#FF8A8D",
          1000: "#FF7C80",
        },
        lavender: {
          DEFAULT: "#BF92C7",
          foreground: "#FFFFFF",
          50: "#FCF9FC",
          100: "#F9F5FA",
          200: "#F2E9F4",
          300: "#ECDFEF",
          400: "#E5D3E9",
          500: "#DFC9E3",
          600: "#D9BEDD",
          700: "#D3B3D8",
          800: "#CCA8D2",
          900: "#C69DCD",
          1000: "#BF92C7",
        },
        grey: {
          DEFAULT: "#3D3D3D",
          50: "#F6F6F6",
          100: "#EEEEEE",
          200: "#DCDCDC",
          300: "#CCCCCC",
          400: "#BABABA",
          500: "#A9A9A9",
          600: "#979797",
          700: "#868686",
          800: "#757575",
          900: "#595959",
          1000: "#3D3D3D",
        },
        neutral: {
          DEFAULT: "#3D3D3D",
          50: "#F6F6F6",
          100: "#EEEEEE",
          200: "#DCDCDC",
          300: "#CCCCCC",
          400: "#BABABA",
          500: "#A9A9A9",
          600: "#979797",
          700: "#868686",
          800: "#757575",
          900: "#595959",
          1000: "#3D3D3D",
        },
        white: "#FFFFFF",
        error: {
          DEFAULT: "#D71A1A",
          foreground: "#FFFFFF",
        },
        warning: {
          DEFAULT: "#F59C00",
          foreground: "#FFFFFF",
        },
        success: {
          DEFAULT: "#57AD57",
          foreground: "#FFFFFF",
        },
        star: "hsl(var(--star))",
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
